import { expect,test } from "@playwright/test";

test("complete keyboard-operable supervised simulation",async({page})=>{
  await page.goto("/");
  await expect(page.getByRole("heading",{name:/Hear every important detail/})).toBeVisible();
  await page.getByRole("button",{name:"Continue locally"}).click();
  await expect(page.getByRole("heading",{name:"A calm, readable way to handle the phone."})).toBeVisible();
  await expect(page.getByText("Real calls off")).toBeVisible();
  await page.getByRole("button",{name:"Create a support case"}).click();
  await page.getByLabel("Your first name").fill("Avery");
  await page.getByLabel("Company name").fill("Northstar Goods");
  await page.getByLabel("Official US support number").fill("(212) 555-0198");
  await page.getByLabel("Describe the issue").fill("A newly delivered item arrived defective and customer support needs to correct the order.");
  await page.getByLabel("Relevant chronology").fill("Item arrived defective yesterday");
  await page.getByLabel("Desired resolution").fill("Replace the defective item at no charge");
  await page.getByLabel("Acceptable alternatives").fill("Refund the item");
  await page.getByLabel("Unacceptable outcomes").fill("Pay a new fee");
  await page.getByLabel("Facts the assistant may use").fill("The item was defective on arrival");
  await page.getByLabel(/I obtained this number/).check();
  await page.getByLabel(/I am calling about my own account/).check();
  await page.getByLabel(/This is not emergency/).check();
  await page.getByRole("button",{name:"Create editable plan"}).click();
  await expect(page.getByRole("heading",{name:"Northstar Goods support request"})).toBeVisible();
  await page.getByLabel("Plan title").fill("Defective item replacement");
  await page.getByLabel("Simulation scenario").selectOption("cancellation-offer");
  await expect(page.getByRole("button",{name:/place real call/i})).toBeDisabled();
  await page.getByRole("button",{name:/Approve plan and start simulation/}).click();
  await expect(page.getByRole("heading",{name:"Call in progress"})).toBeVisible();
  await page.getByRole("button",{name:"Pause agent"}).click();
  await expect(page.getByText("Paused — transcript still active").first()).toBeVisible();
  await page.getByLabel("Say this exactly").fill("Please continue when ready.");
  await page.getByRole("button",{name:"Speak exact text"}).click();
  await page.getByRole("button",{name:"Resume agent"}).click();
  const dialog=page.getByRole("alertdialog");
  await expect(dialog).toBeVisible();
  await expect(dialog).toBeFocused();
  await expect(dialog.getByText("Liaison will not continue until you choose.")).toBeVisible();
  await dialog.getByRole("button",{name:"Approve"}).click();
  await expect(page.getByRole("heading",{name:"Call complete"})).toBeVisible();
  await expect(page.getByText("A concrete outcome was confirmed.")).toBeVisible();
  await expect(page.getByRole("link",{name:"Export text"})).toBeVisible();
  await page.keyboard.press("Tab");
  await expect(page.locator(":focus")).toBeVisible();
});
