import { describe,expect,it } from "vitest";
import { defaultAuthority, type CallState } from "../../src/shared/domain.js";
import { canTransition, detectHighRisk, enforceAuthority, estimateCost, normalizeUsPhone, prohibitedSecretReason, redactText, safeKeyEqual, signToken, transitionState, validateDecision, validateDtmf, validateOutcome, verifyToken } from "../../src/server/core/policy.js";

describe("state machine",()=>{
  const states:CallState[]=["PREPARING","DIALING","CONNECTED","IVR","ON_HOLD","WAITING_FOR_REPRESENTATIVE","DISCLOSING_ASSISTANT","EXPLAINING_ISSUE","AUTHENTICATING","NEGOTIATING","NEEDS_USER","VERIFYING_OUTCOME","ENDING","COMPLETED","FAILED"];
  const allowed:Record<CallState,CallState[]>={PREPARING:["DIALING","FAILED"],DIALING:["CONNECTED","FAILED","ENDING"],CONNECTED:["IVR","WAITING_FOR_REPRESENTATIVE","DISCLOSING_ASSISTANT","ENDING","FAILED"],IVR:["IVR","ON_HOLD","WAITING_FOR_REPRESENTATIVE","DISCLOSING_ASSISTANT","ENDING","FAILED"],ON_HOLD:["ON_HOLD","WAITING_FOR_REPRESENTATIVE","DISCLOSING_ASSISTANT","NEGOTIATING","ENDING","FAILED"],WAITING_FOR_REPRESENTATIVE:["ON_HOLD","DISCLOSING_ASSISTANT","ENDING","FAILED"],DISCLOSING_ASSISTANT:["DISCLOSING_ASSISTANT","EXPLAINING_ISSUE","ENDING","FAILED"],EXPLAINING_ISSUE:["AUTHENTICATING","NEGOTIATING","ON_HOLD","NEEDS_USER","VERIFYING_OUTCOME","ENDING","FAILED"],AUTHENTICATING:["AUTHENTICATING","NEGOTIATING","NEEDS_USER","ON_HOLD","ENDING","FAILED"],NEGOTIATING:["NEGOTIATING","AUTHENTICATING","NEEDS_USER","ON_HOLD","VERIFYING_OUTCOME","ENDING","FAILED"],NEEDS_USER:["AUTHENTICATING","NEGOTIATING","EXPLAINING_ISSUE","VERIFYING_OUTCOME","ENDING","FAILED"],VERIFYING_OUTCOME:["VERIFYING_OUTCOME","NEGOTIATING","NEEDS_USER","ENDING","FAILED"],ENDING:["COMPLETED","FAILED"],COMPLETED:[],FAILED:[]};
  it("accepts every permitted transition and rejects every prohibited transition",()=>{for(const from of states)for(const to of states)expect(canTransition(from,to),`${from} -> ${to}`).toBe(allowed[from].includes(to));expect(()=>transitionState("PREPARING","COMPLETED")).toThrow("ILLEGAL_STATE_TRANSITION")});
});

describe("authority and input policy",()=>{
  it("ships restrictive defaults and preserves hard denials",()=>{expect(defaultAuthority.navigateIvr).toBe("ALLOW");expect(defaultAuthority.disclosePersonalData).toBe("ASK");expect(defaultAuthority.maximumAuthorizedCostCents).toBe(0);expect(enforceAuthority({makePurchase:"ALLOW" as never}).makePurchase).toBe("DENY")});
  it("normalizes only plausible US numbers",()=>{expect(normalizeUsPhone("(212) 555-0198")).toBe("+12125550198");expect(()=>normalizeUsPhone("911")).toThrow("SHORT_OR_EMERGENCY");expect(()=>normalizeUsPhone("+442071838750")).toThrow("INVALID_US")});
  it("detects high-risk use and secret patterns",()=>{expect(detectHighRisk("Call the bank about my credit card")).toContain("financial");expect(prohibitedSecretReason("password: hunter2")).toBe("PASSWORD");expect(prohibitedSecretReason("my code is 123456")).toBe(null)});
  it("validates ordinary and sensitive DTMF",()=>{expect(validateDtmf("12#")).toBe(true);expect(validateDtmf("12345")).toBe(false);expect(validateDtmf("12345",true)).toBe(true);expect(validateDtmf("1A")).toBe(false)});
  it("enforces monetary cap and stale generations",()=>{const base={state:"NEGOTIATING" as const,authority:{...defaultAuthority,maximumAuthorizedCostCents:500},paused:false,pendingApproval:null,disclosureDelivered:true,consentStatus:"ACCEPTED" as const,durationSeconds:10,maximumDurationSeconds:1800,generation:2,expectedGeneration:2,executedKeys:new Set<string>()};const decision={action:"REQUEST_APPROVAL" as const,nextState:"NEEDS_USER" as const,policyReasonCode:"FEE_REQUIRES_APPROVAL",capturedFacts:[],approval:{category:"FINANCIAL" as const,question:"Accept?",representativeRequest:"Fee",proposedSpeech:"Approved",consequences:"A fee",amountCents:600}};expect(validateDecision(decision,base)).toMatchObject({allowed:false,violationCode:"MONETARY_CAP_EXCEEDED"});expect(validateDecision({...decision,approval:{...decision.approval,amountCents:400}},{...base,expectedGeneration:3})).toMatchObject({allowed:false,violationCode:"STALE_GENERATION"})});
  it("blocks substantive speech before disclosure, duplicate actions, and denied approval categories",()=>{const base={state:"CONNECTED" as const,authority:defaultAuthority,paused:false,pendingApproval:null,disclosureDelivered:false,consentStatus:"UNKNOWN" as const,durationSeconds:1,maximumDurationSeconds:1800,generation:1,expectedGeneration:1,executedKeys:new Set<string>()};const speech={action:"SPEAK" as const,text:"Here is the account issue.",nextState:"DISCLOSING_ASSISTANT" as const,policyReasonCode:"EXPLAIN_ISSUE",capturedFacts:[]};expect(validateDecision(speech,base)).toMatchObject({allowed:false,violationCode:"DISCLOSURE_REQUIRED"});const disclosed={...speech,text:"Accessibility disclosure",policyReasonCode:"DISCLOSE_ACCESSIBILITY_ASSISTANT"};expect(validateDecision(disclosed,{...base,executedKeys:new Set(["SPEAK:Accessibility disclosure"])})).toMatchObject({allowed:false,violationCode:"DUPLICATE_EXTERNAL_ACTION"});const approval={action:"REQUEST_APPROVAL" as const,nextState:"NEEDS_USER" as const,policyReasonCode:"CANCEL",capturedFacts:[],approval:{category:"CANCELLATION" as const,question:"Cancel?",representativeRequest:"Cancel",proposedSpeech:"Cancel it",consequences:"Service ends"}};expect(validateDecision(approval,{...base,state:"NEGOTIATING",disclosureDelivered:true,consentStatus:"ACCEPTED",authority:{...defaultAuthority,cancelService:"DENY"}})).toMatchObject({allowed:false,violationCode:"AUTHORITY_DENIED"})});
});

describe("redaction and evidence",()=>{
  it("redacts exact and formatted variants",()=>{const secrets=[{label:"Account",category:"ACCOUNT_NUMBER",value:"1234-5678"}];expect(redactText("Account 1234-5678 / 12345678 / 1234 5678",secrets)).not.toContain("1234")});
  it("removes unsupported fields and downgrades weak resolution",()=>{const turns=[{id:"t1",sequence:1,speaker:"REMOTE" as const,text:"I will submit a request for review.",timestamp:new Date().toISOString()}];const evidence=[{turnId:"t1",exactQuote:"submit a request"}];const report={status:"RESOLVED" as const,summary:{value:"Submitted",evidence},representativeName:{value:"Made Up",evidence:[{turnId:"missing",exactQuote:"No"}]},department:null,caseNumber:null,resolution:{value:"I will submit a request for review.",evidence:[{turnId:"t1",exactQuote:turns[0].text}]},monetaryOutcomes:[],companyCommitments:[],userActions:[],deadlines:[],unresolvedItems:[],endedAt:new Date().toISOString(),durationSeconds:3,estimatedTelephonyCostUsd:0};const cleaned=validateOutcome(report,turns);expect(cleaned.status).toBe("PARTIAL");expect(cleaned.representativeName).toBeNull()});
});

describe("auth, signing, and costs",()=>{
  it("compares access keys and expires signed tokens",()=>{expect(safeKeyEqual("same","same")).toBe(true);expect(safeKeyEqual("same","different")).toBe(false);const token=signToken({callId:"one"},"secret",60);expect(verifyToken<{callId:string}>(token,"secret")?.callId).toBe("one");expect(verifyToken(token,"wrong")).toBeNull();expect(verifyToken(signToken({x:1},"secret",-1),"secret")).toBeNull()});
  it("calculates proportional estimated cost",()=>{expect(estimateCost(300,.084)).toBe(.42);expect(estimateCost(600,.084)).toBe(.84)});
});
