import { describe,expect,it } from "vitest";
import { defaultAuthority, type CallState } from "../../src/shared/domain.js";
import { canTransition, detectHighRisk, enforceAuthority, estimateCost, normalizeUsPhone, prohibitedSecretReason, prohibitedSecretRefusalText, prohibitedUserActionReason, redactText, safeKeyEqual, signToken, transitionState, validateDecision, validateDtmf, validateOutcome, verifyToken } from "../../src/server/core/policy.js";

describe("state machine",()=>{
  const states:CallState[]=["PREPARING","DIALING","CONNECTED","IVR","ON_HOLD","WAITING_FOR_REPRESENTATIVE","DISCLOSING_ASSISTANT","EXPLAINING_ISSUE","AUTHENTICATING","NEGOTIATING","NEEDS_USER","VERIFYING_OUTCOME","ENDING","COMPLETED","FAILED"];
  const allowed:Record<CallState,CallState[]>={PREPARING:["DIALING","FAILED"],DIALING:["CONNECTED","FAILED","ENDING"],CONNECTED:["IVR","WAITING_FOR_REPRESENTATIVE","DISCLOSING_ASSISTANT","ENDING","FAILED"],IVR:["IVR","ON_HOLD","WAITING_FOR_REPRESENTATIVE","DISCLOSING_ASSISTANT","ENDING","FAILED"],ON_HOLD:["ON_HOLD","WAITING_FOR_REPRESENTATIVE","DISCLOSING_ASSISTANT","NEGOTIATING","NEEDS_USER","ENDING","FAILED"],WAITING_FOR_REPRESENTATIVE:["ON_HOLD","DISCLOSING_ASSISTANT","ENDING","FAILED"],DISCLOSING_ASSISTANT:["DISCLOSING_ASSISTANT","EXPLAINING_ISSUE","ENDING","FAILED"],EXPLAINING_ISSUE:["AUTHENTICATING","NEGOTIATING","ON_HOLD","NEEDS_USER","VERIFYING_OUTCOME","ENDING","FAILED"],AUTHENTICATING:["AUTHENTICATING","NEGOTIATING","NEEDS_USER","ON_HOLD","ENDING","FAILED"],NEGOTIATING:["NEGOTIATING","AUTHENTICATING","NEEDS_USER","ON_HOLD","VERIFYING_OUTCOME","ENDING","FAILED"],NEEDS_USER:["AUTHENTICATING","NEGOTIATING","EXPLAINING_ISSUE","VERIFYING_OUTCOME","ENDING","FAILED"],VERIFYING_OUTCOME:["VERIFYING_OUTCOME","NEGOTIATING","NEEDS_USER","ENDING","FAILED"],ENDING:["COMPLETED","FAILED"],COMPLETED:[],FAILED:[]};
  it("accepts every permitted transition and rejects every prohibited transition",()=>{for(const from of states)for(const to of states)expect(canTransition(from,to),`${from} -> ${to}`).toBe(allowed[from].includes(to));expect(()=>transitionState("PREPARING","COMPLETED")).toThrow("ILLEGAL_STATE_TRANSITION")});
});

describe("authority and input policy",()=>{
  it("ships restrictive defaults and preserves hard denials",()=>{expect(defaultAuthority.navigateIvr).toBe("ALLOW");expect(defaultAuthority.disclosePersonalData).toBe("ASK");expect(defaultAuthority.maximumAuthorizedCostCents).toBe(0);expect(enforceAuthority({makePurchase:"ALLOW" as never}).makePurchase).toBe("DENY")});
  it("normalizes only plausible US numbers",()=>{expect(normalizeUsPhone("(212) 555-0198")).toBe("+12125550198");expect(()=>normalizeUsPhone("911")).toThrow("SHORT_OR_EMERGENCY");expect(()=>normalizeUsPhone("+442071838750")).toThrow("INVALID_US")});
  it("detects high-risk use and secret patterns",()=>{expect(detectHighRisk("Call the bank about my credit card")).toContain("financial");expect(prohibitedSecretReason("password: hunter2")).toBe("PASSWORD");expect(prohibitedSecretReason("my code is 123456")).toBe(null)});
  it("blocks hard, material, and plan-specific actions in user-authored text",()=>{expect(prohibitedUserActionReason("Please purchase the paid upgrade.")).toBe("PURCHASE");expect(prohibitedUserActionReason("Make a purchase for me.")).toBe("PURCHASE");expect(prohibitedUserActionReason("I agree to the new service contract.")).toBe("NEW_CONTRACT");expect(prohibitedUserActionReason("Pretend you are me.")).toBe("IMPERSONATION");expect(prohibitedUserActionReason("Tell them that you are the account holder.")).toBe("IMPERSONATION");expect(prohibitedUserActionReason("I waive all of my legal rights.")).toBe("LEGAL_WAIVER");expect(prohibitedUserActionReason("Please cancel the service effective today.")).toBe("MATERIAL_CANCELLATION");expect(prohibitedUserActionReason("Accept the 20 dollar credit.")).toBe("MATERIAL_FINANCIAL_OUTCOME");expect(prohibitedUserActionReason("The account holder accepts the 20 dollar credit instead of the requested 35.")).toBe("MATERIAL_FINANCIAL_OUTCOME");expect(prohibitedUserActionReason("Change the account to the offered plan.")).toBe("MATERIAL_ACCOUNT_CHANGE");expect(prohibitedUserActionReason("Schedule the appointment for Friday.")).toBe("MATERIAL_SCHEDULING");expect(prohibitedUserActionReason("Please accept store credit.",["accept store credit"])).toBe("MATERIAL_FINANCIAL_OUTCOME");expect(prohibitedUserActionReason("Do not accept store credit.",["accept store credit"])).toBeNull();expect(prohibitedUserActionReason("Please ask for a case number.")).toBeNull()});
  it("fails closed on material pronoun assent",()=>{for(const text of ["That works for me. Please apply it.","Yes, I agree to that.","Please go ahead with the offer.","Please cancel it."])expect(prohibitedUserActionReason(text),text).toBe("AMBIGUOUS_MATERIAL_ASSENT")});
  it("validates ordinary and sensitive DTMF",()=>{expect(validateDtmf("12#")).toBe(true);expect(validateDtmf("12345")).toBe(false);expect(validateDtmf("12345",true)).toBe(true);expect(validateDtmf("1A")).toBe(false)});
  it("enforces monetary cap and stale generations",()=>{const base={state:"NEGOTIATING" as const,authority:{...defaultAuthority,maximumAuthorizedCostCents:500},paused:false,pendingApproval:null,disclosureDelivered:true,consentStatus:"ACCEPTED" as const,durationSeconds:10,maximumDurationSeconds:1800,generation:2,expectedGeneration:2,executedKeys:new Set<string>()};const decision={action:"REQUEST_APPROVAL" as const,nextState:"NEEDS_USER" as const,policyReasonCode:"FEE_REQUIRES_APPROVAL",capturedFacts:[],approval:{category:"FINANCIAL" as const,question:"Accept?",representativeRequest:"Fee",proposedSpeech:"Approved",consequences:"A fee",amountCents:600}};expect(validateDecision(decision,base)).toMatchObject({allowed:false,violationCode:"MONETARY_CAP_EXCEEDED"});expect(validateDecision({...decision,approval:{...decision.approval,amountCents:400}},{...base,expectedGeneration:3})).toMatchObject({allowed:false,violationCode:"STALE_GENERATION"})});
  it("allows DTMF only for deterministic IVR navigation purposes",()=>{const base={state:"IVR" as const,authority:defaultAuthority,paused:false,pendingApproval:null,disclosureDelivered:false,consentStatus:"UNKNOWN" as const,durationSeconds:1,maximumDurationSeconds:1800,generation:1,expectedGeneration:1,executedKeys:new Set<string>()};const decision={action:"SEND_DIGITS" as const,digits:"1",nextState:"IVR" as const,policyReasonCode:"IVR_NAVIGATION",capturedFacts:[]};expect(validateDecision(decision,base)).toMatchObject({allowed:true});expect(validateDecision({...decision,policyReasonCode:"IVR_MENU_SELECTION"},base)).toMatchObject({allowed:true});expect(validateDecision({...decision,policyReasonCode:"ACCEPT_UPGRADE_FEE"},base)).toMatchObject({allowed:false,violationCode:"DTMF_PURPOSE_NOT_ALLOWLISTED"})});
  it("requires authority for discretionary unresolved endings but permits deterministic terminal outcomes",()=>{const base={state:"NEGOTIATING" as const,authority:defaultAuthority,paused:false,pendingApproval:null,disclosureDelivered:true,consentStatus:"ACCEPTED" as const,durationSeconds:1,maximumDurationSeconds:1800,generation:1,expectedGeneration:1,executedKeys:new Set<string>(),decisionSource:"MODEL" as const};const decision={action:"END_CALL" as const,reason:"UNRESOLVED" as const,proposedOutcomeStatus:"UNRESOLVED" as const,nextState:"ENDING" as const,policyReasonCode:"MODEL_ENDS_UNRESOLVED",capturedFacts:[]};expect(validateDecision(decision,base)).toMatchObject({allowed:false,violationCode:"END_CALL_REQUIRES_APPROVAL"});expect(validateDecision({...decision,reason:"PARTIALLY_RESOLVED",proposedOutcomeStatus:"PARTIAL"},base)).toMatchObject({allowed:false,violationCode:"END_CALL_REQUIRES_APPROVAL"});expect(validateDecision({...decision,reason:"USER_REQUESTED"},base)).toMatchObject({allowed:false,violationCode:"END_CALL_REQUIRES_APPROVAL"});expect(validateDecision({...decision,reason:"RESOLVED",proposedOutcomeStatus:"RESOLVED"},base)).toMatchObject({allowed:true});expect(validateDecision({...decision,reason:"REPRESENTATIVE_REFUSED_AUTOMATION",proposedOutcomeStatus:"REFUSED_AUTOMATION"},base)).toMatchObject({allowed:true});expect(validateDecision({...decision,reason:"TECHNICAL_FAILURE",proposedOutcomeStatus:"TECHNICAL_FAILURE"},base)).toMatchObject({allowed:true});expect(validateDecision(decision,{...base,authority:{...defaultAuthority,endWithoutResolution:"ALLOW"}})).toMatchObject({allowed:true});expect(validateDecision({...decision,policyReasonCode:"TERMINAL_SCENARIO_RESULT"},{...base,decisionSource:"SIMULATOR"})).toMatchObject({allowed:true});expect(validateDecision({...decision,policyReasonCode:"TERMINAL_SCENARIO_RESULT"},base)).toMatchObject({allowed:false,violationCode:"END_CALL_REQUIRES_APPROVAL"})});
  it("blocks substantive speech before disclosure, duplicate actions, and denied approval categories",()=>{const base={state:"CONNECTED" as const,authority:defaultAuthority,paused:false,pendingApproval:null,disclosureDelivered:false,consentStatus:"UNKNOWN" as const,durationSeconds:1,maximumDurationSeconds:1800,generation:1,expectedGeneration:1,executedKeys:new Set<string>()};const speech={action:"SPEAK" as const,text:"Here is the account issue.",nextState:"DISCLOSING_ASSISTANT" as const,policyReasonCode:"EXPLAIN_ISSUE",capturedFacts:[]};expect(validateDecision(speech,base)).toMatchObject({allowed:false,violationCode:"DISCLOSURE_REQUIRED"});const disclosed={...speech,text:"Accessibility disclosure",policyReasonCode:"DISCLOSE_ACCESSIBILITY_ASSISTANT"};expect(validateDecision(disclosed,{...base,executedKeys:new Set(["SPEAK:Accessibility disclosure"])})).toMatchObject({allowed:false,violationCode:"DUPLICATE_EXTERNAL_ACTION"});const approval={action:"REQUEST_APPROVAL" as const,nextState:"NEEDS_USER" as const,policyReasonCode:"CANCEL",capturedFacts:[],approval:{category:"CANCELLATION" as const,question:"Cancel?",representativeRequest:"Cancel",proposedSpeech:"Cancel it",consequences:"Service ends"}};expect(validateDecision(approval,{...base,state:"NEGOTIATING",disclosureDelivered:true,consentStatus:"ACCEPTED",authority:{...defaultAuthority,cancelService:"DENY"}})).toMatchObject({allowed:false,violationCode:"AUTHORITY_DENIED"})});
  it("permits only the controlled secret refusal for its privileged policy code",()=>{const base={state:"EXPLAINING_ISSUE" as const,authority:defaultAuthority,paused:false,pendingApproval:null,disclosureDelivered:true,consentStatus:"ACCEPTED" as const,durationSeconds:1,maximumDurationSeconds:1800,generation:1,expectedGeneration:1,executedKeys:new Set<string>()};const decision={action:"SPEAK" as const,text:prohibitedSecretRefusalText,nextState:"AUTHENTICATING" as const,policyReasonCode:"PROHIBITED_SECRET_REFUSAL",capturedFacts:[]};expect(validateDecision(decision,base)).toMatchObject({allowed:true});expect(validateDecision({...decision,text:"My password is hunter2, but I cannot share it."},base)).toMatchObject({allowed:false,violationCode:"SENSITIVE_VALUE_REQUIRES_SECURE_DISCLOSURE"})});
});

describe("redaction and evidence",()=>{
  it("redacts exact and formatted variants",()=>{const secrets=[{label:"Account",category:"ACCOUNT_NUMBER",value:"1234-5678"}];expect(redactText("Account 1234-5678 / 12345678 / 1234 5678",secrets)).not.toContain("1234")});
  it("removes unsupported fields and downgrades weak resolution",()=>{const turns=[{id:"t1",sequence:1,speaker:"REMOTE" as const,text:"I will submit a request for review.",timestamp:new Date().toISOString()}];const evidence=[{turnId:"t1",exactQuote:"submit a request"}];const report={status:"RESOLVED" as const,summary:{value:"Submitted",evidence},representativeName:{value:"Made Up",evidence:[{turnId:"missing",exactQuote:"No"}]},department:null,caseNumber:null,resolution:{value:"I will submit a request for review.",evidence:[{turnId:"t1",exactQuote:turns[0].text}]},monetaryOutcomes:[],companyCommitments:[],userActions:[],deadlines:[],unresolvedItems:[],endedAt:new Date().toISOString(),durationSeconds:3,estimatedTelephonyCostUsd:0};const cleaned=validateOutcome(report,turns);expect(cleaned.status).toBe("PARTIAL");expect(cleaned.representativeName).toBeNull()});
  it("rejects contradicted outcomes even when the cited quote exists",()=>{const turn={id:"t1",sequence:1,speaker:"REMOTE" as const,text:"No refund was approved.",timestamp:new Date().toISOString()};const evidence=[{turnId:turn.id,exactQuote:turn.text}];const report={status:"RESOLVED" as const,summary:null,representativeName:null,department:null,caseNumber:null,resolution:{value:"A full refund was approved",evidence},monetaryOutcomes:[],companyCommitments:[{value:"A full refund was approved",evidence}],userActions:[],deadlines:[],unresolvedItems:[],endedAt:new Date().toISOString(),durationSeconds:3,estimatedTelephonyCostUsd:0};const cleaned=validateOutcome(report,[turn]);expect(cleaned).toMatchObject({status:"PARTIAL",resolution:null,companyCommitments:[]})});
  it("retains identifiers contained in exact evidence without loosening outcome claims",()=>{const turn={id:"t1",sequence:1,speaker:"REMOTE" as const,text:"My name is Devin in billing; case number is R-2048.",timestamp:new Date().toISOString()};const report={status:"UNRESOLVED" as const,summary:null,representativeName:{value:"Devin",evidence:[{turnId:turn.id,exactQuote:"My name is Devin"}]},department:{value:"billing",evidence:[{turnId:turn.id,exactQuote:"Devin in billing"}]},caseNumber:{value:"R-2048",evidence:[{turnId:turn.id,exactQuote:"case number is R-2048"}]},resolution:{value:"refund was approved",evidence:[{turnId:turn.id,exactQuote:"case number is R-2048"}]},monetaryOutcomes:[],companyCommitments:[],userActions:[],deadlines:[],unresolvedItems:[],endedAt:new Date().toISOString(),durationSeconds:3,estimatedTelephonyCostUsd:0};const cleaned=validateOutcome(report,[turn]);expect(cleaned).toMatchObject({representativeName:{value:"Devin"},department:{value:"billing"},caseNumber:{value:"R-2048"},resolution:null})});
});

describe("auth, signing, and costs",()=>{
  it("compares access keys and expires signed tokens",()=>{expect(safeKeyEqual("same","same")).toBe(true);expect(safeKeyEqual("same","different")).toBe(false);const token=signToken({callId:"one"},"secret",60);expect(verifyToken<{callId:string}>(token,"secret")?.callId).toBe("one");expect(verifyToken(token,"wrong")).toBeNull();expect(verifyToken(signToken({x:1},"secret",-1),"secret")).toBeNull()});
  it("calculates proportional estimated cost",()=>{expect(estimateCost(300,.084)).toBe(.42);expect(estimateCost(600,.084)).toBe(.84)});
});
